type requests{
        _id: ID!,
        worker: users!,
        job: jobs!,
        user: users!,
        request: String!,
        address: String!,
        time: String!,
        status: Int!
}

input requestInput {
        worker: ID!,
        job: ID!,
        user: ID!,
        request: String!,
        address: String!,
        time: String!,
        status: Int!
}

input updateRequest{
        id: ID!,
        status: Int!
}