type messages{
        _id: ID!
        users: [users]!
        messages: [imsg]!
}

type imsg {
        message: String!,
        user: String!
}

type posMsg {
        _id: ID!
        name: String!,
        image: String!,
        num: Int!
}