type messages{
        _id: ID!
        users: [users]!
        messages: [message]!
}

type message{
        messages: String!
        user: [users]!
}

type userMessage{
        message: String!,
        user: ID!
}