type messages{
        _id: ID!
        users: [ID]!
        messages: [message]!
}

type message{
        messages: String!
        user: [users]!
}

type userMessage{
        message: String!,
        user: String!
}

type imsg {
        message: String!,
        user: String!
}