type users{
        _id: ID!
        name: String!,
        email: String!,
        image: String!,
        createdAt: String!
        updatedAt: String!
        messages: [userMessage]
}

type userMessage{
        _id: ID!
        user: [users]!
}

