type users{
        _id: ID!
        name: String!,
        email: String!,
        image: String!,
        createdAt: String!,
        updatedAt: String!,
        rating: Float!,
}

type nearWorkers{
        _id: ID!,
        name: String!,    
        image: String!,
        rating: String!,
        jobs: [workerJobs]!
}

type workerJobs{
        name: String!
        image: String!
}