type jobs{
        _id: ID!,
        image: String!,
        name: String!,
        workers: [jobUser]!,
        average: Float!,
        colour: String!
}

type jobUser{
        user: [users]!
        price: Float!
        type: Int!
}


input userInput {
        id: ID!
        user: ID!
        price: Float!
        type: Int!
}